project_id = "mpvsxmwiriarcwuqmsfu"

[functions.send-password-reset-otp]
verify_jwt = false

[functions.verify-otp-reset-password]
verify_jwt = false

[functions.analyze-dumping-report]
verify_jwt = true