// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpvsxmwiriarcwuqmsfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wdnN4bXdpcmlhcmN3dXFtc2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDU2NTQsImV4cCI6MjA2MzU4MTY1NH0.hve2qa3uEsBTP5a-cjK9JpDs-Gg6zMr7IUcO7xHvzcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);